// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbDAQPb0sZly6QolOfEZeVVsv6DqarpZI',
    appId: '1:730352069421:android:cfd0e029a57dbe221e41a4',
    messagingSenderId: '730352069421',
    projectId: 'quickcart-7086c',
    storageBucket: 'quickcart-7086c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBxBBP0Ye6nWY47NF8qGmk3biID1ht8Cc',
    appId: '1:730352069421:ios:07362d22a0faf1df1e41a4',
    messagingSenderId: '730352069421',
    projectId: 'quickcart-7086c',
    storageBucket: 'quickcart-7086c.appspot.com',
    androidClientId: '730352069421-c2h0cukaln56ju4klf058pr6jraatm4k.apps.googleusercontent.com',
    iosClientId: '730352069421-oql3d8mnukubonmrgtg3o4li1dt8ooq3.apps.googleusercontent.com',
    iosBundleId: 'com.quickcart.user.quickcartUser',
  );
}
