name: quickcart_resto
description: "A restaurant module for quickcart."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.3
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_crashlytics: ^3.5.4
  firebase_messaging: ^14.9.1
  firebase_storage: ^11.7.4
  fl_chart: ^0.62.0
  flutter_config_plus: ^1.1.1
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.1.0
  flutter_typeahead: ^5.2.0
  flutter_zoom_drawer: ^3.2.0
  font_awesome_flutter: ^10.7.0
  fpdart: ^1.1.0
  get: ^4.6.6
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  logger: ^2.2.0
  lottie: ^3.1.0
  onesignal_flutter: ^3.5.1
  open_file: ^3.3.2
  # Maps can change to osm library
  open_street_map_search_and_pick: ^0.1.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  timelines: ^0.1.0
  tuple: ^2.0.2
  uuid: ^4.4.0
  video_player: ^2.8.6

  extended_themes:
    path: ../extended_themes

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/lottie/